vdopiasample  ;  MID  ; INGESTOR ; ETL ;  vdopia-etl=7
vdopiasample ; MID ; JOINER ; ETL ; vdopia-etl=4
vdopiasample  ;  HIGH  ; WRANGLER ; ETL ;  vdopia-etl=7
vdopiasample-bid  ;  MID  ; VALIDATOR ; ETL ;  vdopia-etl=3
